In [1]:
import numpy as np
import pandas as pd

# 20 inbuilt methods on numpy

1) np.sort:
creates a sorted copy on array.
Example:

In [2]:
a = np.array([3,6,4,7,8,2,3,2])
print(np.sort(a))

[2 2 3 3 4 6 7 8]


2) np.arrange
returns evenly spaced values within a given interval
Example:


In [3]:
np.arange(0,20,2)


                

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

3) np.zeros:
Return a new array of given shape and type, filled with zeros.
Example:

In [4]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

4) np.ones:
Return a new array of given shape and type, filled with ones.
Example:

In [6]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

5) np.linspace:
Return evenly spaced numbers over a specified interval.
Example

In [7]:
np.linspace(0,18,6)

array([ 0. ,  3.6,  7.2, 10.8, 14.4, 18. ])

6) np.floor:
rounds down and returns the largest integer less than or equal to a given number.
Example:

In [8]:
a = np.array([-9, -1.5, -0.2, 0.2, 3.8, 1.7, 10.0])
np.floor(a)

array([-9., -2., -1.,  0.,  3.,  1., 10.])

7) np.reshape:
Gives a new shape to an array without changing its data.
Example:

In [9]:
x = np.arange(8).reshape((8, 1))
print(x)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


8) np.ceil:
rounds up a number to the nearest integer, if necessary and returns the result.
Example:

In [10]:
x = np.array([3, -1.5, -0.2, 0.2, 2.5, 1.7, 4.0])
np.ceil(x)

array([ 3., -1., -0.,  1.,  3.,  2.,  4.])

9) np.absolute:
Calculate the absolute value element-wise.
Example:

In [11]:
x = np.array([-9, -10,8,-5,-6])
np.absolute(x)

array([ 9, 10,  8,  5,  6])

10) np.resize:
Return a new array with the specified shape.
Example:


In [12]:
x=np.array([[4,1],[2,6]])
np.resize(x,(4,3))

array([[4, 1, 2],
       [6, 4, 1],
       [2, 6, 4],
       [1, 2, 6]])

11) np.add:
use to add arguments element wise. #come back to this for the second way/example.
Example:

In [13]:
np.add(90,5)

95

12) np.ones_like
Return an array of ones with the same shape and type as a given array.
Example:

In [14]:
y = np.arange(3)
y

array([0, 1, 2])

In [15]:
np.ones_like(y)

array([1, 1, 1])

13) np.alen:
Return the length of the first dimension of the input array.
Example:

In [16]:
x = np.zeros((9,7,5)) 
x.shape[2]

5

In [17]:
np.alen(x)

9

14) np.all:
Test whether all array elements along a given axis evaluate to True.
Example:

In [18]:
np.all([[True,True],[True,True]])

True

In [19]:
np.all([[False, False],[True,True]])

False

In [20]:
np.all([[False, False],[False, False]])

False

15) np.any:
Test whether any array element along a given axis evaluates to True.
Example:

In [21]:
np.any([[False, True],[False, False]])

True

16) np.arccos:
Trigonometric inverse cosine, element-wise.
Example:

In [22]:
np.arccos([0, 1.])

array([1.57079633, 0.        ])

17) np.arcsin:
Trigonometric inverse sine, element-wise.
Example:

In [23]:
np.arcsin([0,1])

array([0.        , 1.57079633])

18) np.zeros_like:
Return an array of zeros with the same shape and type as a given array.
Exampl:

In [24]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
 np.zeros_like(y)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

19) np.eye:
creates an identity matrix.
Example:

In [26]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

20) np.randint:
Return random integers from low (inclusive) to high (exclusive).
Example:


In [27]:
np.random.randint(2,10,10)

array([6, 3, 5, 8, 2, 4, 9, 3, 2, 2])

# 20 inbuilt methods on pandas

In [28]:
import numpy as np
import pandas as pd

1) pd.Series:
this is a one dimensional ndarray with axis labels.
Example:

In [29]:
d={'adult':18, 'teenager':16}
ser=pd.Series(data=d, index=['adult', 'teenager'])


In [30]:
ser

adult       18
teenager    16
dtype: int64

2) pd.DataFrame:
Two-dimensional, size-mutable, potentially heterogeneous tabular data.
Example:

In [31]:
d = {'col1': ['Adult', 'Teenager'], 'col2': [18, 16]}
df = pd.DataFrame(data=d)

In [32]:
df

col1  col2
0     Adult    18
1  Teenager    16

2) pd.date_range:
used to return a fixed frequency DatetimeIndex, you must specify the start and end.
Example:

In [33]:
pd.date_range(end='1/1/2018', periods=8)



DatetimeIndex(['2017-12-25', '2017-12-26', '2017-12-27', '2017-12-28',
               '2017-12-29', '2017-12-30', '2017-12-31', '2018-01-01'],
              dtype='datetime64[ns]', freq='D')

3) pd.concat:
Concatenate pandas objects along a particular axis with optional set logic
along the other axes.
Example:

In [34]:
A1 = pd.Series(['100', '95','90'])
B2 = pd.Series(['89', '85','80'])


In [35]:
pd.concat([A1, B2])

0    100
1     95
2     90
0     89
1     85
2     80
dtype: object

4) pd.cut:
Bin values into discrete intervals.
Exampe:

In [36]:
pd.cut(np.array([2, 7, 8, 4, 6, 9]), 6)

[(1.993, 3.167], (6.667, 7.833], (7.833, 9.0], (3.167, 4.333], (5.5, 6.667], (7.833, 9.0]]
Categories (6, interval[float64, right]): [(1.993, 3.167] < (3.167, 4.333] < (4.333, 5.5] < (5.5, 6.667] < (6.667, 7.833] < (7.833, 9.0]]

5) pd.array:
creates an array.
Example:

In [37]:
pd.array([100, 50, np.nan])


<IntegerArray>
[100, 50, <NA>]
Length: 3, dtype: Int64

6) pd.Categorical:
Represent a categorical variable in classic fashion. Missing values are not included in catagory.
Example:

In [38]:
 numbers = pd.Categorical([1, 2, 3, 1, 2, 3, np.nan])

In [39]:
numbers

[1, 2, 3, 1, 2, 3, NaN]
Categories (3, int64): [1, 2, 3]

In [40]:
number = pd.Categorical([1, 0, 3, 7, 2, 3, np.nan])

In [41]:
number

[1, 0, 3, 7, 2, 3, NaN]
Categories (5, int64): [0, 1, 2, 3, 7]

7) pd.BooleanDtype:
This is an extention dtype for boolean data.
Example:

In [42]:
pd.BooleanDtype

pandas.core.arrays.boolean.BooleanDtype

8) pd.Index: #check index.slice
This is the basic object storing axis labels for all pandas objects.
Example:

In [43]:
pd.Index([8,9,7,6])

Int64Index([8, 9, 7, 6], dtype='int64')

9) pd.eval:
Evaluate a Python expression as a string using various backends.
Example(adding a new column to a dataset):


In [44]:
df = pd.DataFrame({"names": ["Belinda", "Aramide"], "age": [10, 20]})


In [45]:
df

names  age
0  Belinda   10
1  Aramide   20

In [46]:
pd.eval("double_age = df.age * 2", target=df)

names  age  double_age
0  Belinda   10          20
1  Aramide   20          40

10) pd.Grouper:
A Grouper allows the user to specify a groupby instruction for an object.
Example:

In [49]:
df = pd.DataFrame({"Animal": ["Falcon", "Parrot", "Falcon", "Falcon", "Parrot"],
"Speed": [10, 5, 90, 300, 10],})

In [50]:
df

Animal  Speed
0  Falcon     10
1  Parrot      5
2  Falcon     90
3  Falcon    300
4  Parrot     10

In [58]:
df.groupby(pd.Grouper(key="Animal")).mean()

Speed
Animal            
Falcon  133.333333
Parrot    7.500000

11) pd.melt:
Used to create a specific format of the DataFrame object where one or more columns work as identifiers.
Example:

In [59]:
df = pd.DataFrame({'A': {0: 'a', 1: 'b', 2: 'c'},'B': {0: 1, 1: 3, 2: 5},'C': {0: 2, 1: 4, 2: 6}})

In [60]:
df

A  B  C
0  a  1  2
1  b  3  4
2  c  5  6

In [61]:
pd.melt(df, id_vars=['A'], value_vars=['B'])

A variable  value
0  a        B      1
1  b        B      3
2  c        B      5

12) pd.Interval:
An index of interval objects that are all closed on the same side.
Example:

In [65]:
Range = pd.Interval(left=4, right=8)

In [66]:
Range

Interval(4, 8, closed='right')

In [67]:
6 in Range #checking to see if 6 belongs to the interval within 4 and 8

True

In [68]:
9 in Range #checking to see if 9 belongs to the interval within 4 and 8

False

13) pd.lreshape:
Reshape wide-format data to long format. This is a generalized inverse of DataFrame.pivot. 
Example:

In [72]:
data = pd.DataFrame({'votes1': [114, 873], 'votes2': [989, 126],'team': ['APC', 'PDP'],
                     'year1': [2007, 2007], 'year2': [2008, 2008]})

In [73]:
data

votes1  votes2 team  year1  year2
0     114     989  APC   2007   2008
1     873     126  PDP   2007   2008

In [74]:
pd.lreshape(data, {'year': ['year1', 'year2'], 'votes': ['votes1', 'votes2']})

team  year  votes
0  APC  2007    114
1  PDP  2007    873
2  APC  2008    989
3  PDP  2008    126

14) pd.factorize:
This method is useful for obtaining a numeric representation of an array when all that matters is identifying distinct values.
Example:

In [78]:
numbers, alphabets = pd.factorize(['b', 'b', 'a', 'c', 'b'])

In [79]:
numbers

array([0, 0, 1, 2, 0], dtype=int64)

In [80]:
alphabets

array(['b', 'a', 'c'], dtype=object)

15) pd.CategoricalDtype:
Type for categorical data with the categories and orderedness.
Example:

In [82]:
X = pd.CategoricalDtype(categories=['b', 'a'], ordered=True)
pd.Series(['a', 'b', 'a', 'c'], dtype=t)

0      a
1      b
2      a
3    NaN
dtype: category
Categories (2, object): ['b' < 'a']

16) pd.interval_range:
 Used to return a fixed frequency IntervalIndex.
Example:

In [84]:
 pd.interval_range(start=5, end=20)

IntervalIndex([(5, 6], (6, 7], (7, 8], (8, 9], (9, 10] ... (15, 16], (16, 17], (17, 18], (18, 19], (19, 20]], dtype='interval[int64, right]')

17) pd.infer_freq:
Infer the most likely frequency given the input index. If the frequency is
uncertain, a warning will be printed.
Example:

In [91]:
x= pd.date_range(start='2020/12/01', end='2020/12/30', periods=30)

In [92]:
pd.infer_freq(x)

'D'

18) pd.crosstab:
Compute a simple cross tabulation of two (or more) factors.
Example:

In [94]:
a = np.array(["foo", "foo", "foo", "foo", "bar", "bar",
               "bar", "bar", "foo", "foo", "foo"], dtype=object)
b = np.array(["one", "one", "one", "two", "one", "one",
"one", "two", "two", "two", "one"], dtype=object)
c = np.array(["dull", "dull", "shiny", "dull", "dull", "shiny",
"shiny", "dull", "shiny", "shiny", "shiny"],
dtype=object)


In [95]:
pd.crosstab(a, [b, c], rownames=['a'], colnames=['b', 'c'])

b    one        two      
c   dull shiny dull shiny
a                        
bar    1     2    1     0
foo    2     2    1     2

19) pd.qcut:
Disctretize variable into equal-sized buckets based on rank or based on sample quantiles.
Example:


In [98]:
 pd.qcut(range(8), 3, labels=["good", "better", "best"])

['good', 'good', 'good', 'better', 'better', 'best', 'best', 'best']
Categories (3, object): ['good' < 'better' < 'best']

20) pd.isnull:
Detect missing values for an array-like object.
Example:

In [99]:
pd.isna(pd.NA)

True